cache_transceiver_config:
  backend: UCX
  max_tokens_in_buffer: 4096
context_parallel_size: 16
cp_config:
  cp_type: HELIX
  fifo_version: 2
  tokens_per_block: 32
  use_nccl_for_alltoall: false
cuda_graph_config:
  enable_padding: true
  max_batch_size: 64
enable_attention_dp: false
enable_autotuner: false
enable_lm_head_tp_in_adp: false
kv_cache_config:
  dtype: fp8
  enable_block_reuse: false
  free_gpu_memory_fraction: 0.8
  tokens_per_block: 32
max_batch_size: 64
max_input_len: 252928
max_num_tokens: 128
max_seq_len: 261632
moe_config:
  backend: CUTEDSL
moe_expert_parallel_size: 32
num_postprocess_workers: 4
pipeline_parallel_size: 1
print_iter_log: true
stream_interval: 20
tensor_parallel_size: 2
trust_remote_code: true
